# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: qiweiRot schedule

on:
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 18表示北京时间早上2点
    - cron: "0 23 * * *"
    # 中午 11 点
    # - cron: "15 2 * * *" 

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 16.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: "npm"
    steps:
      - uses: actions/checkout@v2
      - name: Run Project
        # 通过 群机器人 发送
        # run: cd widget/WeCom && npm install && cd src && node webhook.js ${{ secrets.HOOK }} 
        # 通过 应用 发送
        run: cd widget/WeCom && npm install -g pnpm && pnpm install && cd src && node sendByApp.js ${{ secrets.QW_APP_S }}
